# Generated by Django 4.2.5 on 2023-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=15)),
                ('goals', models.IntegerField()),
                ('jerseyno', models.IntegerField()),
                ('age', models.IntegerField()),
                ('redcards', models.IntegerField()),
                ('numberofmatches', models.IntegerField()),
            ],
        ),
    ]
